### ISSUE TITLE
How to index by STI model type

### ISSUE THREAD

**Issue by jonsgold** [pat/thinking-sphinx#1001]
[Copied from [this stackoverflow question](http://stackoverflow.com/q/38833445/1772)]

Is there any way to index the type of an STI model (a polymorphic model's association in Ruby) and not itself? For example, I have a model Comment:

```
class Comment < ActiveRecord::Base
  belongs_to :commenter, polymorphic: true
  ...
end
```

Is it possible to get sphinx to index commenters and not comments?

To be specific, instead of sphinx.conf looking like

```
source comment_core_0
{
  ...
  sql_query = SELECT SQL_NO_CACHE comments.id * 60 + 2 AS id, 
    'Comment' AS sphinx_internal_class_name, 
    comments.id AS sphinx_internal_id, 
    'Comment' AS sphinx_internal_class
    ...
}
```

I would want sphinx.conf to look like:

```
source comment_core_0
{
  ...
  sql_query = SELECT SQL_NO_CACHE comments.commenter_id * 60 + 2 AS id, 
    commenter_type AS sphinx_internal_class_name, 
    comments.commenter_id AS sphinx_internal_id, 
    commenter_type AS sphinx_internal_class
    ...
}
```

Thanks

**Comment by pat** [comment]
I'm afraid this isn't possible with Thinking Sphinx - it is built to expect an index maps to a single model. Also, in the situation you've described (if you were to make something like this work in Sphinx directly, rather than TS), you could end up with duplicate records if a commenter has more than one comment.

You'd be much better to have indices for each commenter type and search across all of these indices at once.

**Comment by jonsgold** [comment]
I see, thanks anyway. I'll close this issue.
