### ISSUE TITLE
Setting up TS to run on a different Host than the Rails App

### ISSUE THREAD

**Issue by nartz** [pat/thinking-sphinx#1005]
Is there support for running Sphinx on a different host than same as the Rails application? If so, what is the best pattern to do that? 

For clarification, i'm wondering if its possible to also use the same rake tasks, etc, i.e. rake ts:start / stop / index

**Comment by pat** [comment]
What you'll want to do is configure the address used by Sphinx to be a specific IP or host:
http://freelancing-gods.com/thinking-sphinx/advanced_config.html#daemon-address
Then, deploy your app to both servers, and run all Sphinx-related rake tasks on the server that you want Sphinx to be running on.

If you're using any of the delta approaches, you'll need to use a background job approach (e.g.: ts-delayed-deltas, ts-sidekiq-deltas, etc) and have the job processing happen on the Sphinx server (because the jobs need file-system access to Sphinx indices).

**Comment by nartz** [comment]
to clarify, we have say webserver on 10.0.0.1 and searchd on 10.0.0.2 (appcode is deployed on both). I assume we put 10.0.0.2 as the daemon address for appcode/ts on 10.0.0.1, however, doesnt the appcode then on 10.0.0.2 also need to specify this (separately) then as 'localhost', meaning two different config files?

**Comment by pat** [comment]
Having it set to just 10.0.0.2 and that code being on both machines should be fine. My understanding is Sphinx will bind to that specific host, but that's fine given - I presume? - all searching will be running through TS, and thus will use that setting consistently.

**Comment by nartz** [comment]
okay gotcha, thanks!
