### ISSUE TITLE
FacetSearch facet hash results with concatenated string of attributes

### ISSUE THREAD

**Issue by abhinavvalue** [pat/thinking-sphinx#1006]
**Indice establishment_index.rb**
ThinkingSphinx::Index.define :establishment, :with => :active_record, :delta => true do
  indexes est_cost_ranges.range, as: :price_range, :sortable => true, :facet => true
  has est_cost_ranges.id, :as => :est_cost_range_id, :facet => true
end
**EstCostRange Model**
class EstCostRange < ActiveRecord::Base
  # attr_accessible :title, :body
  attr_accessible :range

  has_and_belongs_to_many :establishments
end

**Results**
irb(main):254:0> @est_cost_range_facets = Establishment.facets(:max_matches => 10000, :conditions =>{:status=>"published", :city=>"bangalore"},:facets => [:price_range])[:price_range]

=> {"351-500 1351-1500"=>1, ""=>17, "851-1000 1351-1500"=>1, "351-500 851-1000"=>7, "351-500 501-850"=>2, "501-850 851-1000"=>3, "501-850 1001-1350"=>1, "351-500"=>2, "251-350"=>3, "351-500 1001-1350"=>1, "Above 1500"=>1, "Above 1500 351-500"=>1, "251-350 Above 1500"=>1, "501-850"=>1}

**Comment by abhinavvalue** [comment]
Why above issue closed?

**Comment by pat** [comment]
Fields are single string values for each record - so that means in your case, for each establishment, each of its price ranges get concatenated together into a single string.

Unfortunately, while Sphinx has support for multi-value _attributes_, strings are not a supported multi-value type (only integers, bigints, and timestamps). So, what I'd recommend you do in this case is use the `est_cost_range_id` attribute for your facet generation, and translate the ids through to their range labels. I realise this isn't nearly as elegant, but I can't think of a better way to do this with Sphinx.
