### ISSUE TITLE
rake tasks fail with zero exit status

### ISSUE THREAD

**Issue by quinn** [pat/thinking-sphinx#1014]
If there is an error in sphinx, the rake script still exits with zero. Makes it hard to use with anything that provides automation (capistrano, etc) because there is an assumption that failure will exit with non-zero, especially in a scenario where output is suppressed and you can't see the ERROR output.   Is this intentional behavior  or difficult in any way ? thanks :)

**Comment by pat** [comment]
I have just pushed some changes that should take care of this for the most part. You can give it a spin using the `develop` branch:

```ruby
gem 'thinking-sphinx', '~> 3.2.0',
  :git    => 'git://github.com/pat/thinking-sphinx.git',
  :branch => 'develop',
  :ref    => '21897c7259'
```

A few things to note: `ts:start` and `ts:stop` are now verbose by default. You can control the verbosity by using Rake's `--quiet` flag (for no Sphinx output, only TS info messages) or `--silent` (for no output at all beyond exceptions).

Also: sometimes Sphinx command-line tools return a status of zero even though there is a fatal error. There's nothing that _changes_ this behaviour in TS (it will pass through whatever Sphinx's status code is, even if it is arguably misleading). Changing TS to be a little 'smarter' about this is probably infeasible because `system` calls (which are used in the verbose approaches) don't return their CLI output - thus, there's no easy way to scan for 'FATAL' being printed to the terminal (which would otherwise be my go-to string to match on).

Still, I figure this is all better than nothing! Do let me know if you notice any issues :)

**Comment by pat** [comment]
Also, a touch further detail: I've noticed the zeros status codes when Sphinx fails to start due to already being running as determined by either the pid file being present, or the port being used. I guess it could be argued that they're not _fatal_ errors due to the daemon actually being present.

Trying to run `ts:index` when there are no indices defined, or any task where the configuration file is somehow invalid, though, will fail with a status code of 1.
