### ISSUE TITLE
Very slow real time indexing comparing to SQL-backed one

### ISSUE THREAD

**Issue by hipertracker** [pat/thinking-sphinx#1026]
On my MBP with SSD and the table having over 3 mln records `ts:rebuild` takes  57 seconds. But 
`ts:regenerate` takes 10 minutes! That's the huge difference. Why is that?

**Comment by pat** [comment]
With SQL-backed indices, Sphinx is able to access your database directly via SQL queries. With real-time indices, though, each ActiveRecord instance is loaded and used to gain the data - so, you've got the overhead of Ruby and Rails to contend with.

Real-time indices have the option of [defining an initial scope](http://freelancing-gods.com/thinking-sphinx/indexing.html#conditions) - which can allow you to specify preloaded associations to optimise the loading of your objects. So, this may help improve the performance?

Still, SQL-backed indices are almost always going to be faster to process. The downside is that when your records change, SQL-backed indices can't update a single record with your new details. You'd need to use delta processing, or otherwise your Sphinx documents are going to be out-of-date with any changes since the last time you ran `rake ts:index`/`rake ts:rebuild`. Also, with SQL-backed indices you're limited to SQL statements to generate data for Sphinx, whereas real-time indices gives you the power of Ruby for data manipulation.

**Comment by hipertracker** [comment]
Is `ts:generate' working like `ts:reindex` except it uses RT indeces? With SQL-backed indeces I can run `ts:reindex` without putting down my web app. Is it something similar if I use real time indeces?

**Comment by hipertracker** [comment]
Maybe I could run manually something using `ThinkingSphinx::RealTime.callback_for(:verse)`. I tried, it does not index anything. Maybe there is another way?

**Comment by pat** [comment]
With SQL-backed indices:

* Use `ts:index` regularly to keep your indices data up-to-date.
* Use `ts:rebuild` only when you've changed your Sphinx schemas, and yes, this will involve Sphinx being down while it runs.

With real-time indices:

* Use the real-time callbacks to keep your indices data up-to-date immediately.
* Use `ts:generate` semi-regularly to confirm your indices data are up-to-date (in case any data is modified and callbacks aren't invoked).
* Use `ts:regenerate` only when you've changed your Sphinx schemas. This will mean Sphinx is down briefly at the beginning of the task, but then it'll be running though not all data will be present until this task has finished.

If your data is changing frequently, then I'd recommend real-time indices (`ts:generate` may only need to be run once a day, if you're quite sure the callbacks should catch all data changes?).

However, if your data is changing infrequently, then SQL-backed indices may be a better approach, especially if having your search matches slightly out-of-sync is not a big problem.

The real-time callbacks can _only_ be used for models with real-time indices. Sphinx only allows immediate updates for real-time indices, not SQL-backed indices.

If you want to invoke a real-time update at some other point (besides callbacks), you can do the following:

```ruby
ThinkingSphinx::RealTime.callback_for(:verse).after_save(verse)
```

**Comment by pat** [comment]
And just to be clear: both `ts:generate` and `ts:index` will not stop Sphinx, and thus your app should continue to work fine while they're running.

**Comment by hipertracker** [comment]
That's great explanation. Thank you.
