### ISSUE TITLE
Many delta index guard files preventing indexing

### ISSUE THREAD

**Issue by airblade** [pat/thinking-sphinx#1028]
Hi Pat,

I'm seeing 0-300 messages per day in my Rails logs like this: "Guard file for index sample_delta exists, not indexing".

As a quick hack I have a cron job which removes the guard files every 5 minutes:

```
*/5 * * * * find /path/to/my/app/shared/db/sphinx/*.tmp -mmin +5 -exec rm {} \;
```

But I'd like to stop the guard files from being created, or rather from not being removed, in the first place.  However I can't figure out how to begin investigating what's going on with them.  Do you have any suggestions?

I'm running a dated stack of Rails 3.2.22.4, Thinking Sphinx 3.1.2, Sphinx 2.2.4-id64-dev (r4699).

Many thanks!

**Comment by pat** [comment]
Hi Andy,

First question is: what are you using to process delta requests? Is it via background workers, or the default inline approach?

I'm wondering if there are parallel delta indexing processes happening, which would explain why the conflicts are taking place. It may be worth adding some uniqueness constraints around delta processing if that's not already happening?

Otherwise: are you seeing any exceptions related to delta processing that may result in the guard files persisting for longer than they should?

**Comment by airblade** [comment]
Thanks, Pat.

My index looks like this:

```ruby
ThinkingSphinx::Index.define :sample, with: :active_record, delta: true do
  ...
end
```

I'm just using the default approach for processing the delta updates; no delayed deltas in the background or timestamp deltas.  Should I still be adding some uniqueness constraints to the delta processing?  (And if so, how?)

I have a few background jobs generally, but I don't think any of them update any sample records.

I'm not quite sure how the delta indexing works.  Let's say:

- a guard file for the sample delta index is left lying around for some reason;
- sample A is updated;
- the guard file is deleted by cron;
- sample B is updated.

At this point, is A's update in the delta index or do we need a full re-index for Sphinx to see it?

I was also wondering how a guard file could be left lying around.  As far as I can tell, the code [removes it after use in an ensure block](https://github.com/pat/thinking-sphinx/blob/cad9d58ec15dad0eacd296ecdf0a8cb5ab6e93aa/lib/thinking_sphinx/guard/files.rb#L18).  So what could sidestep this?  When you talk about exceptions related to delta processing, what should I be looking for?

Sorry about all the questions!

**Comment by pat** [comment]
No need to apologise for questions - that's what the issues are for!

With regards to your situation with samples A & B - sample A will indeed be included in the delta index call run by the change to sample B.

And you're right, there is an ensure block to make sure files are deleted. However, if the overarching Ruby process gets killed (say, as part of deploys), then that ensure block isn't run.

With the default delta approach, there is the possibility of parallel delta updates happening if your webserver (Puma? Unicorn?) has more than one worker process/thread. Two requests could come in at pretty much the same time, both modifying sample objects, and thus both running delta updates. One will be successful, one will be stopped by the lock file. However, if these delta calls overlap, then I'd be pretty sure both changes are in the database, and thus the single successful delta call will include both records (like your example situation). Still, you will see the message in the logs about the guard file being present.

If you switch to ts-sidekiq-delta or ts-delayed-delta (or ts-resque-delta, though that might be a little out-of-date), then you can funnel delta updates through their processing and have some control over uniqueness constraints. The specifics of that depend on how you've got them set up - if they're running in a serial manner (globally or for the ts_delta queue), then that'll sort it out easily enough.

ts-delayed-delta will actually check for existing unprocessed delta jobs, so it should be pretty good about keeping the processing happening in a serial manner. For Sidekiq, you could use something like [sidekiq-unique-jobs](https://rubygems.org/gems/sidekiq-unique-jobs) to manage things as well. The end result of this is that you shouldn't see any guard warnings in your logs. Whether making this change is worth the effort though is up to you!

Still, I think it'd be good to get the delta processing happening in a background worker, because then it removes time required for the Sphinx updates out of your web responses, thus making for a faster experience :)

**Comment by airblade** [comment]
That's good to know about A and B.

I hadn't appreciated that a log message might simply indicate two simultaneous updates, with both changes making it into the delta index, instead of an orphaned guard file blocking all updates.

I use Unicorn so there could indeed be multiple processes updating samples at the same time.  

Looking at the logs I'm prepared to believe most of the messages could be "innocent".  However there must be at least some where updates have been missed because I ran into that situation a couple of times (leading to this issue).

So, as I understand it, when an update is missed it could be due to:

- a simultaneous update where one change was dropped (simultaneous updates sound racy);
- the process getting killed before the ensure block is run.

In the first option the guard file will be cleaned up but in the second it will be orphaned.

I'm not sure which I'm running into or whether it's both.  I can't think when a worker process would be killed: deployments allow existing requests to complete, and only requests lasting longer than 30s are killed before completion (and I don't have any of those).

I think I should add a bit of logging to that ensure block to find out what's going on.

I use Delayed Job so ts-delayed-delta is a good possibility.  I'll look into that too...

**Comment by pat** [comment]
Your summary sounds correct, and it does sound like something is causing guard file problems, I'm just not sure what it is. If you're able to add in some extra logging, that sounds like a good first step. And yes, if you can give ts-delayed-delta a shot, that might help as well :)

**Comment by pat** [comment]
Hi Andy - it's been a few months since this issue was last referenced, so I'm going to close it. Feel free to discuss the issue further, though - and if we need to, I can always re-open it :)

**Comment by airblade** [comment]
Hi Pat, sorry for leaving this dangling.

I opened this issue because I was seeing some updates not being delta-indexed, and when I investigated I found all the "not indexing" messages.  So I assumed that was probably the cause.

However a couple of weeks ago I realised the problem was the updates were bypassing ActiveRecord callbacks, which is why they weren't in the delta index.  I fixed this and haven't seen any missing updates since.

I think the guard file was a red herring and the messages were just caused by Unicorn's workers updating things at the same time, as one would expect.

Thanks for all your help with this – I always learn new things when I open an issue on one of your repos :)
