### ISSUE TITLE
Upgrade issue

### ISSUE THREAD

**Issue by mtamhankar1** [pat/thinking-sphinx#1052]
I just tested upgrading from thinking-sphinx 3.1.4 to 3.3.0 and ran into a small issue.

In 3.1.4, I used to be able to filter based on an attribute passing it as a string. Something like: `Article.with_communties(['1','3']).search('something')`

After the upgrade, sphinx started complaining about `unexpected QUOTED_STRING`. I can easily fix this by doing `Article.with_communities([1,3]).search('something')` (passing array of integers instead of array of strings).

Was there an intentional change made to cause this?

**Comment by pat** [comment]
Ah, this is actually related to a change in the Riddle gem (which generates the SphinxQL queries). The upcoming TS release (which is the commits in the `develop` branch) tries to cast filter values to their appropriate types, but in the long run I definitely want to remove that - it's just a stop-gap solution to make the transition easier.

The change has been made because Sphinx now allows for filters on string attributes (whereas previously they'd been only for grouping/ordering), and so the SphinxQL generation needs to pay closer attention to types - it can't presume that every string value passed in should actually be treated as an integer (Sphinx treats booleans and timestamps as integers, hence why it was a safe assumption previously). This means that Riddle will put quotes around string values in the query, and this is why you're getting the `QUOTED_STRING` error.

I'll try to get a new release of TS out soon, but your options in the meantime are either: use the latest in the `develop` branch (here's the diff: https://github.com/pat/thinking-sphinx/compare/v3.3.0...develop - mostly testing changes and bug fixes); or, review your code and ensure you're passing in appropriately typed values for any attribute filters.

**Comment by mtamhankar1** [comment]
We are in a position to ensure the types are correct for the filter values, so we will likely be moving forward with an upgrade to 3.3.. I just wanted to understand a little about why things were changing, so this helps.

Thanks!
