### ISSUE TITLE
Capistrano deploy feature

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1053]
Hi Pat,

We've developed some code that only reindexes (and restarts sphinx) when the indexes have changed on the server. Is that something that you would be interested in a pull request for? Our issue was that deploys were taking a long time. We frequently add new fields to our indexes.

Adam

**Comment by pat** [comment]
Hi Adam,

Thanks for offering this! I'm not sure I'd accept a pull request though - if I had my time again, I would have extracted the Capistrano/TS integration into its own gem, rather than TS itself. That said, if you want to open source what you've done - even if it's just as a gist linked to from this issue, that'd be great. I'm sure others would find it useful.

Cheers

Pat

**Comment by atomical** [comment]
Thanks for the response. I will do that once I get permission to open source the code.
