### ISSUE TITLE
future of Sphinx Search

### ISSUE THREAD

**Issue by jogaco** [pat/thinking-sphinx#1056]
The Sphinx Search project has been inactive for the last 7 months. A rather unusual long period!

I wonder if it's time to move to another solution: solr, ES, ...

**Comment by pat** [comment]
Just because something has been updated, doesn't mean it's no longer useful! Of course, if there are flaws in Sphinx that are causing problems for you, then definitely evaluate other options - but I know I'm using Sphinx without problems in several projects. Seven months isn't _that_ long (and indeed, there was a commit just the other day: https://github.com/sphinxsearch/sphinx/commit/e93969e20920737a24ad9b55651bb9b72fd81174) - and I put more value in stability and function, rather than the frequency of updates.

Use what's best for your projects and your colleagues - Sphinx, ElasticSearch, Solr, whatever - but that's not really a Thinking Sphinx issue :)

**Comment by jogaco** [comment]
I hope you are right, as I like Sphinx Search.
