### ISSUE TITLE
rails 5.1.1 deprecation warning for changed?

### ISSUE THREAD

**Issue by valdis** [pat/thinking-sphinx#1059]
in `lib/thinking_sphinx/active_record/callbacks/delta_callbacks.rb`
```
    48: def new_or_changed?
 => 49:   instance.new_record? || instance.changed?
    50: end
```

throws

```
DEPRECATION WARNING: The behavior of `changed?` inside of after callbacks will be changing in the next version ofRails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes?` instead. (called from changed? at app/models/<model.rb>)
```

P.S. thanks for the gem, it has been very useful!

**Comment by pat** [comment]
Thanks for pointing this out. I'm struggling to get the same warning locally though. Can you confirm which versions of Rails and Thinking Sphinx you're using?

**Comment by avitus** [comment]
I'm getting these deprecation warnings with Thinking Sphinx 3.3 and Rails 5.1

**Comment by avitus** [comment]
@pat I actually appear to have an example of each of the scenarios you mentioned.

In one case it is an after_create callback which updates a field in a model instance based on three other fields.

In the second case, I'm essentially creating a type of linked list so when one model instance changes, 'next' and 'prev' pointers in associated models are updated.

Not sure whether that helps at all.

**Comment by pat** [comment]
@avitus it may have taken me two months to respond, but that information is definitely helpful.

From what I can tell, both from the scenarios you're describing and the testing I've done locally: these warnings only crop up because an `after_x` callback invokes a further change on the model, which in turn invokes the `before_save` on the delta callbacks. I'd expect the internal behaviour here to be fine - it's just that the Rails deprecation warnings aren't smart enough to know about inner callbacks, hence the misleading warning. Not sure if there's much to be done about this. 🤷‍♂️

**Comment by pat** [comment]
Closing this, as I think it's more an issue with Rails' deprecation warnings not picking up on nested callbacks.
