### ISSUE TITLE
Order by timestamp has no effect

### ISSUE THREAD

**Issue by nvma** [pat/thinking-sphinx#1065]
Hello, Pat! We have a weird situation where our order by stopped working with timestamps. It does work with ids but doesn't work with updated_at \ created_at.

Here's the index itself.
```
ThinkingSphinx::Index.define :product, with: :real_time do
  # fields
  indexes name, sortable: true
  indexes description, sortable: true

  indexes category_names

  # properties
  set_property min_prefix_len: 1

  # attributes
  has category_ids, type: :integer, multi: true
  has created_at, type: :timestamp
  has updated_at, type: :timestamp
end
```
So this query works as expected
```
2.4.1 :015 > Product.search "", order: 'id DESC'
  Sphinx Query (2.1ms)  SELECT * FROM product_core WHERE sphinx_deleted = 0 ORDER BY id DESC LIMIT 0, 20
  Sphinx  Found 201 results
  Product Load (1.5ms)  SELECT "products".* FROM "products" WHERE "products"."id" IN (201, 200, 199, 198, 197, 196, 195, 194, 193, 192, 191, 190, 189, 188, 187, 186, 185, 184, 183, 182)
```
But this query, and ASC likewise, doesn't work at all. No errors and no clues. Hoping for your insight.
```
2.4.1 :014 > Product.search "", order: 'updated_at DESC'
  Sphinx Query (3.4ms)  SELECT * FROM product_core WHERE sphinx_deleted = 0 ORDER BY updated_at DESC LIMIT 0, 20
  Sphinx  Found 201 results
  Product Load (1.5ms)  SELECT "products".* FROM "products" WHERE "products"."id" IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20)
```
Cheers and thanks for the amazing gem!

**Comment by pat** [comment]
Hmm, I'm not spotting anything obviously wrong in what you're doing! Which version of Thinking Sphinx are you using?

**Comment by nvma** [comment]
@pat we're at latest setup, I think. `sphinx 2.2.11` and `ts - 3.3.0`, the thing that it has worked until recently, we're trying to backtrack everything step by step but with no success yet. Do think it's remotely possible that timezone and locale could interfere with this?

**Comment by pat** [comment]
Okay, I'd certainly expect v3.3.0 to be working fine.

The next things I'd recommend trying:

* Run `rake ts:stop`, delete all the index and binlog files, and then run `rake ts:regenerate` to get everything loaded again. It's a bit more manual, but doesn't hurt to double-check.
* Use the MySQL CLI tool to connect to Sphinx directly and run the SphinxQL query to confirm whether the data on that side of things is being sorted as you'd expect. `mysql --host 127.0.0.1 --port 9306` or equivalent should do the trick (the host is required to ensure TCP rather than a UNIX socket is used).

As for timezones… as long as you're storing things consistently, I'd expect that to be fine and have no impact here.

**Comment by nvma** [comment]
Hey, @pat! What you suggested did actually work, not really sure what exactly but thorough purging and rebuilding yielded success. Thanks a lot, mate. You rock!

**Comment by pat** [comment]
Great to hear! I know TS had a bug in previous versions around clearing out data, though I'm quite sure that should be working reliably now. Still, I'm glad the more manual approach helped sort it out 👍
