### ISSUE TITLE
What rake task will run only update the delta indexes?

### ISSUE THREAD

**Issue by nihe33** [pat/thinking-sphinx#1080]
I have a table xdocuments (I wrote about it earlier). Also, I have the old API is developed on Python which gets data and writes to the xdocuments.

For such situations, I can't use real_time indices, because thinking sphinx index updates real_time via callbacks. I can't because my model does not know that there are new data (API Python).

Then I'm left with one option - to use delta indexes. I liked the idea of the attribute is set to `delta = 0`, which is described [here](https://freelancing-gods.com/thinking-sphinx/deltas.html). But I don't understand how it is possible to index just delta indexes via rake task? If I run `rake ts:index`, judging by the logs, it will be indexed and core and delta. But I want to index only the delta. Once upon a time (I read in some article) was the task rake `ts:in:delta`, but it doesn't work.

PS Use the `ts-datetime-delta gem`, I would not want.

And were I can find rake task for merge indexes?

**Comment by pat** [comment]
You're correct that real-time indices operate by a callback. However, delta indices work the same way - they're invoked by callbacks when a record is updated or created. There's no rake task to process just the delta indices, but it's easy enough to make your own task to do it. The code you'll want to invoke is:

```
ThinkingSphinx::Configuration.instance.controller.index "xdocument_delta"
```

There are caveats with this approach, though:

* The original records in the core index aren't marked as 'deleted'. That means searches will still match on their old data, as well as their new data in the delta indices.
* You'll need to make sure that the delta flag is set to true/1 yourself (if the column default is this, that should be fine for new records, but updates will require you to set it yourself).

And no matter what, when you're using delta indices, you still need to run a full index regularly - otherwise the deltas just get bigger and bigger, and thus become slow to process. There is no functionality in Thinking Sphinx for merging indices, I'm afraid. The last time I tried that out, I didn't find it reliable, but that was many years ago.

Also, the `ts:in:delta` task that old documentation refers to is for the `ts-datetime-delta` gem, which is no longer supported (it was never as popular as the delta column approach, and so wasn't migrated to work with TS v3+).

**Comment by nihe33** [comment]
> The original records in the core index aren't marked as 'deleted'. That means searches will still match on their old data, as well as their new data in the delta indices.

Tell me a little more, I did not understand you very well.

> You'll need to make sure that the delta flag is set to true/1 yourself (if the column default is this, that should be fine for new records, but updates will require you to set it yourself).

Yeah, I'll try to set this attribute in the API . Or do through a default column parameter in the database.

> And no matter what, when you're using delta indices, you still need to run a full index regularly - otherwise the deltas just get bigger and bigger, and thus become slow to process. 

Yes, of course.

> There is no functionality in Thinking Sphinx for merging indices, I'm afraid. The last time I tried that out, I didn't find it reliable, but that was many years ago.

Hmm ... But in different articles they write that delta indexes can be very large and you must make a merger. Although perhaps the articles were old, I do not remember.

However ... Delta indices, working every hour, in six months will be large, can they somehow "clean"? Or, when you do full indexing every day, will they clean themselves?


> The code you'll want to invoke is:

Is there a way to pass multiple indexes? Otherwise, the indexer will run several times instead of one.

**Comment by pat** [comment]
>> The original records in the core index aren't marked as 'deleted'. That means searches will still match on their old data, as well as their new data in the delta indices.

> Tell me a little more, I did not understand you.

Sorry, my explanation wasn't very clear. Let's use an example:

* There's a document with the name "Anne" - and the name is a field. This document is present in the core index.
* I then update the document to have the name "Alice", and the delta flag is set to true/1.
* If I search for "Alice", I won't see this document. If I search for Anne, I'll still see it, because it matches on the core index.
* I then process the delta index.
* If I search for "Alice", I will see this document, because it matches on the delta index. If I search for "Anne", I'll also see it, because it still matches on the core index.
* Thinking Sphinx adds a boolean attribute called `sphinx_deleted` to every index. As part of the standard delta processing, the core record has `sphinx_deleted` set to true, and filters out these records in every search.
* So, once `sphinx_deleted` is set to true in the core index, then "Alice" will match the document, and "Anne" will not.
* But because you're not using the in-built delta processing of Thinking Sphinx, this attribute updating isn't taking place.

You _can_ set the `sphinx_deleted` flag with some Ruby code. The catch is that Sphinx's record ids are different to model primary keys, because Sphinx expects all records to be unique - even across indices. So, you can't have a record with an id of 1 in both article_core and user_core.

Thinking Sphinx works around this by having an offset for each index, and uses the primary key as part of the calculation. You'll see this math happening in the generated SQL queries within your Sphinx configuration file.

The simplistic Ruby code to mark a single record as deleted is as follows:

```ruby
ThinkingSphinx::Deltas::DeleteJob.new("xdocument_core", record_id).perform
```

Of course, that's only useful if you know how to calculate the record id yourself… A more lengthy but more intelligent alternative:

```ruby
# presuming there's a model Article which has a Sphinx index
# and an instance of article in the variable `article`:

configuration = ThinkingSphinx::Configuration.instance
configuration.preload_indices
configuration.indices_for_references(:article).each do |index|
  # skip delta indices - we only want to use the core ones.
  next if index.delta?

  # the `document_id_for_instance` method calculates the
  # unique record id that Sphinx expects.
  ThinkingSphinx::Deltas::DeleteJob.new(
    index.name, index.document_id_for_instance(article)
  ).perform
end
```

I realise that's a _lot_ of information. I hope it makes sense!

> However ... Delta indices, working every hour, in six months will be large, can they somehow "clean"? Or, when you do full indexing every day, will they clean themselves?

A full indexing sets the delta flags of all records back to false/0 after processing each core index, and also then processes the delta indices - which will find no matching data, and thus be empty again.

Also, in regards to the above example - a full index also sets the `sphinx_deleted` attributes back to false.

> Is there a way to pass multiple indexes? Otherwise, the indexer will run several times instead of one.

Yes! Sorry, my example was a bit brief - you can pass in as many indices to that call as you like:

```ruby
ThinkingSphinx::Configuration.instance.controller.index(
  "xdocument_delta", "article_delta", "user_delta"
)
```

**Comment by nihe33** [comment]
Sorry for not having replied to you.

Yes, now I understood. Interesting situation. It turns out that in my situation must do the following:
1. After deleting or modifying records, using callback to execute 

`ThinkingSphinx::Deltas::DeleteJob.new("xdocument_core", record_id).perform`

2. When adding a record to set the flag delta=1

And all?


```
ThinkingSphinx::Configuration.instance.controller.index(
  "xdocument_delta", "article_delta", "user_delta"
)
```

Maybe the gem has a method to retrieve a list of all the delta indexes?

**Comment by pat** [comment]
I'm glad my previous comment helped :)

> After deleting or modifying records, using callback to execute ...

For any changes made on the Rails side of things, there will be callbacks automatically added already, because you've set the `:delta` option in the index definitions.

> When adding a record to set the flag delta=1

You also need to do this when updating a record.

> Maybe the gem has a method to retrieve a list of all the delta indexes?

The easiest way is the following:

```ruby
configuration = ThinkingSphinx::Configuration.instance
configuration.preload_indices

delta_index_names = configuration.indices.select(&:delta?).collect(&:name)
configuration.controller.index *delta_index_names
```

**Comment by nihe33** [comment]
> For any changes made on the Rails side of things, there will be callbacks automatically added already, because you've set the :delta option in the index definitions.

Okay, but then where to do this?

`ThinkingSphinx::Deltas::DeleteJob.new("xdocument_core", record_id).perform`


> You also need to do this when updating a record.

Ok, thank you.

**Comment by pat** [comment]
> Okay, but then where to do this?
> 
> `ThinkingSphinx::Deltas::DeleteJob.new("xdocument_core", record_id).perform`

You only need to do this (and setting the delta flag) when you're making changes to your data which will _not_ invoke Rails callbacks.

You mentioned a Python API - if you're changing data through that, make sure it's setting the delta flag accordingly, and you'll need to find some way to call this Ruby code as well.

**Comment by nihe33** [comment]
> You mentioned a Python API - if you're changing data through that, make sure it's setting the delta flag accordingly, and you'll need to find some way to call this Ruby code as well.

This API only retrieves the data but does not change them (in any way). All changes happen only on the side Rails for the web application.

> You only need to do this (and setting the delta flag) when you're making changes to your data which will not invoke Rails callbacks.

Ok, I'll try.

**Comment by nihe33** [comment]
It seems everything works fine. Thank you for help!
If you don't mind, I have a final question.

I can't find in the documentation of the determination of the status of indexing. Ie I would like to know if there is now indexing or not?

This will allow me to record the status in the database and based on that make the decision whether to re-launch the indexing or you need to wait.

**Comment by pat** [comment]
Flying Sphinx actually does this automatically. [Index guard files](https://freelancing-gods.com/thinking-sphinx/rake_tasks.html#index-guard-files) are created within the indices directory while indexing occurs, then removed once the indexing is done.

Does this fit what you need?

**Comment by pat** [comment]
Closing this issue as it's been dormant for a month - but feel free to still ask questions (or create new issues) if needed :)
