### ISSUE TITLE
"with" Query Issue

### ISSUE THREAD

**Issue by ncri** [pat/thinking-sphinx#1084]
I have a sphinx query giving me a result where I think it shouldn't give any:

```
CompanyProfile.search("spiegelbild", :with=> {:organization_status=>1})
Sphinx Query (5.6ms)  SELECT * FROM `organization_profile_core` WHERE MATCH('spiegelbild @sphinx_internal_class_name (CompanyProfile)') AND `organization_status` = 1 AND `sphinx_deleted` = 0 LIMIT 0, 20
  Sphinx  Found 1 results

=> [#<CompanyProfile id: 834033 ....]
```

However that profile has organization_status = 0:

```
Sphinx Query (0.5ms)  REPLACE INTO organization_profile_core (id, ....., `organization_status`, `organization_account_status`) VALUES (5004200, ..., 0, 0)
```

Even a full reindex doesn't help.

Here is the relevant part of the index definition:

```
has organization.status, as: 'organization_status', type: :integer
```

And `CompanyProfile.find(834033).organization.status => 0`

Using thinking-sphinx (3.2.0) with real time indexes.

**Comment by pat** [comment]
Well this is odd indeed!

I guess I'd start by connecting to Sphinx in the CLI via mysql (along the lines of `mysql --host 127.0.0.1 --port 9306` - the host argument is required to force mysql to use a TCP connection rather than a UNIX socket). Try `SELECT * FROM organization_profile_core WHERE sphinx_internal_id = 834033` - does that return just the single record? What's the value of `organization_status`?

Also, if you can, I'd recommend upgrading TS to at least [v3.3.0](https://github.com/pat/thinking-sphinx/releases/tag/v3.3.0) - there's a bug fix there related to clearing out index files as part of `ts:regenerate`, which may be part of the problem for you (perhaps old data's getting persisted somehow).

**Comment by ncri** [comment]
Thanks, the update did the trick! Sorry, should have done that first. But maybe the info you gave here will help solving future issues. ;-)

**Comment by pat** [comment]
Great to know it's working now :)

**Comment by ncri** [comment]
Oh, but well, now doing a full reindex with flying sphinx gives me an error:

```
bundler: failed to load command: flying-sphinx (/app/vendor/bundle/ruby/2.4.0/bin/flying-sphinx)
NoMethodError: undefined method `generate' for #<ThinkingSphinx::RakeInterface:0x0000000ed16b78>
```

Any idea how to solve this?

**Comment by ncri** [comment]
So far we used a specific ref on github of flying sphinx because that was the only way we could get all work nicely together:

gem 'flying-sphinx', github: 'flying-sphinx/flying-sphinx', ref: "16bef180f8838a33e94c2fd6016e19d5c67bfd14"

I will try to update it. Our setup can't break much more than it is broken now... ;-)

**Comment by ncri** [comment]
Wohoo and an update also solved that. ;-)

**Comment by pat** [comment]
For what it's worth: I've been working on the upcoming releases of TS and FS gems where all the `ts` rake tasks will work in both environments, thus making the `fs`/`flying-sphinx` commands deprecated. There's still a couple of things to clean up, and I'm waiting on Rails 5.2.0 proper to be released so I can confirm it all works with that, but it's not too far away!

**Comment by ncri** [comment]
Sounds great! :) Thanks.
