### ISSUE TITLE
"changed?" method will be changed in rails

### ISSUE THREAD

**Issue by joker-777** [pat/thinking-sphinx#1085]
Hello,

we get a depreciation warning which indicates that you use the method `changed?` which will be changed in future.

```
DEPRECATION WARNING: The behavior of `changed?` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_changes?` instead.
```

We get this error because we update the model in an `after_create` callback which also uses thinking sphinx.

More information which methods will change can be found here https://github.com/rails/rails/pull/25337#issuecomment-225166796

**Comment by pat** [comment]
I _believe_ this happens because TS fires its own change to the model (I'm presuming you're using deltas), which means there's another full cycle of callbacks in the inner save - and in there, it's calling `changed?` within the `before_save`. Rails' deprecation warning doesn't distinguish about the inner callback within the outer callback.

This has also been discussed in #1059.

**Comment by joker-777** [comment]
OK, it makes sense. Thanks a lot for your response.
