### ISSUE TITLE
Reindexing and indexing with Sidekiq

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1113]
We have a cron job that runs `rake ts:index` at 12AM every day. We're starting to see some issues where data is missing from the index. Could that be because a delta Sidekiq job is running at the same time as indexes are being updated? Is there locking that takes place to prevent a race condition?

**Comment by pat** [comment]
I'm presuming from discussions in #1114 that deltas are perhaps not in play now?

I would expect that data should continue to be present - at least, by the time the `ts:index` task is done, everything should be there and consistent. If you're finding this problem is still happening though, do let me know (and it'd be useful to know which version of Thinking Sphinx is being used).

**Comment by atomical** [comment]
The version is 3.1.4, but we'll soon be upgrading to 4.0.0. Looking forward to using the one at a time indexing strategy. That may be the cause of some of our difficulties during deploy. I'll reopen the issue if I discover something.
