### ISSUE TITLE
Guard file exists will reindex?

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#1121]
``` Sphinx  Guard file for index user_delta exists, not indexing: /var/www/shared/db/sphinx/ts-user_delta.tmp.```

We are seeing a lot of log entries with this warning. Do these jobs retry?

**Comment by pat** [comment]
They won't retry, but if everything is working correctly, they shouldn't need to.

I'm presuming this is due to concurrent delta requests - one delta request won't occur while another is in process, due to the lock file existing. However, the delta processing will catch all changes in the database, not just the one that prompted the delta callback to fire.

If you wanted to avoid these log messages, then you could change the ts_delta job queue to have a single worker (thus, avoiding concurrent processes), but that may be more hassle than it's worth, and yeah, things should still be working even with these log entries.

**Comment by atomical** [comment]
It's possible to have the deltas for two different tables indexing at the same time, right? That's the advantage of using more than one thread for ts_delta job queue?

**Comment by pat** [comment]
Ah, very good point, yes.
