### ISSUE TITLE
How to remove update queries during rebuild

### ISSUE THREAD

**Issue by Haseeb717** [pat/thinking-sphinx#1128]
I am using master/slave databases for my app and have 2 slave , one for sphinx and one for users and as per rule 1 master

Slave databases are set read only and we cant rebuild sphinx on slave. So I want to remove the update queries which run when we update sphinx and will do through script on master directly.

Which update queries run when we rebuild or re index sphinx?

**Comment by pat** [comment]
The query that runs on update can be found in the `sql_query_pre` settings of your generated configuration file. It'll be something like this:

```
sql_query_pre = UPDATE `articles` SET `delta` = 0 WHERE `delta` = 1
```

To stop this statement from existing in your configuration file, you can create your own subclass of the delta processor you're using (which is `ThinkingSphinx::Deltas::DefaultDelta` if you're using the default deltas - `:delta => true` - or otherwise whatever class you're referring to in your `:delta` setting. This subclass should override the default `reset_query` method and return nil.

```ruby
class ReadOnlyDeltas < ThinkingSphinx::Deltas::DefaultDelta
  def reset_query
    nil
  end
end
```

And then, use that new subclass in your delta settings:

```ruby
ThinkingSphinx::Index.define(
  :article, :with => :active_record, :delta => ReadOnlyDeltas
) do
  # ...
end
```

Of course, you'll need to run the `UPDATE` statements yourself on your write-access database (and for what it's worth, I highly recommend changing the terminology from master/slave to write-access/read-only or something similar).

**Comment by Haseeb717** [comment]
Hi @pat thank you for your reply
let me try this and come back

**Comment by pat** [comment]
Closing this issue as it's been dormant for over a month - but feel free to post further comments if needed :)
