### ISSUE TITLE
Ambiguous fields

### ISSUE THREAD

**Issue by lHydra** [pat/thinking-sphinx#1155]
Hi!

Can you please explain me

I have the index file:

```
ThinkingSphinx::Index.define 'course', with: :active_record do
  indexes "name", as: :course_name
  indexes lectern.name, as: :lectern
end
```

Both tables have a field `name` and when I run `rake ts:rebuild` I get the error:

`ERROR: index 'course_core': sql_range_query: ERROR:  column reference "name" is ambiguous`

And if we look at the file `development.sphinx.conf` we can see that no table specified for the **name** field, but for the **id** field it is.

`sql_query = SELECT "courses"."id"::bigint * 4 + 0 AS "id", name AS "course_name", "lecterns"."name" AS "lectern"...`

So, I must specify in my index file a field with a table to solve the error with ambiguous fields.
`indexes "courses.name", as: :course_name`

Is this is a issue? Maybe we should explicitly assign the table for all fields by default?

**Comment by pat** [comment]
Hi George,

The issue here is that you shouldn't use strings for field/attribute definitions - they should be method calls (like you've done with `lectern.name`), and if they're columns in the main model being indexed (in your case, Course), then they don't need an association prefix.

This way, Thinking Sphinx will then add the table reference in automatically to avoid any ambiguity:

```ruby
ThinkingSphinx::Index.define :course, with: :active_record do
  indexes name, as: :course_name
  indexes lectern.name, as: :lectern
end
```
