### ISSUE TITLE
Errno::EACCES (Permission denied - searchd.pid)

### ISSUE THREAD

**Issue by mcmegavolt** [pat/thinking-sphinx#434]
Hello!

On production server I get this error when try to save Post or create a new one:

```
Errno::EACCES (Permission denied - /var/www/myapp/shared/tmp/searchd.pid):
  app/controllers/postings_controller.rb:40:in `update'
```

**searchd** is running and searching works perfect on a web-site

Sphinx 2.0.4-release (r3135)
thinking-sphinx-2.0.14
Rails 3.2.6

Please, help!

**Comment by MaicolBen** [comment]
I've the same problem, but the web server is not root, and if I don't run sphinx as root because throws: 
'rake aborted! Errno::EACCES: Permission denied', the detailed log is:

    /var/deploy/bumpup/web_head/releases/20150810144039/tmp/binlog 
    /var/deploy/bumpup/web_head/shared/bundle/ruby/1.9.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/configuration.rb:97:in `render_to_file' 
    /var/deploy/bumpup/web_head/shared/bundle/ruby/1.9.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:24:in `configure' 
    /var/deploy/bumpup/web_head/shared/bundle/ruby/1.9.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/rake_interface.rb:35:in `index' 
    /var/deploy/bumpup/web_head/shared/bundle/ruby/1.9.1/gems/thinking-sphinx-3.1.4/lib/thinking_sphinx/tasks.rb:9:in `block (2 levels) in ' Tasks: TOP =&gt; ts:index (See full trace by running task with --trace)

**Comment by pat** [comment]
It seems it can't create that binlog path due to permissions… so you may need to check that all the directories created in `/var/deploy/bumpup/web_head/` have appropriate permissions/owners.

Also, I highly recommend having a binlog path set in `config/thinking_sphinx.yml` that's within the shared directory, so the reference is always consistent across multiple releases. http://freelancing-gods.com/thinking-sphinx/deployment.html

**Comment by MaicolBen** [comment]
Thanks @pat !
