### ISSUE TITLE
ThinkingSphinx::SphinxError: no enabled local indexes to search

### ISSUE THREAD

**Issue by railsfactory-aruns** [pat/thinking-sphinx#652]
In model,
define_index do
    set_property :delta => true
    set_property :docinfo => 'extern'
    set_property :min_word_len => 1
    set_property :wordforms => 'lib/word.txt'
    set_property :stopwords => 'lib/stop.txt'

```
indexes :name 
indexes :description
indexes places(:country), :as => :country
indexes guide_tags(:name_en), :as => 'tag_names_en', :separator => ' '
indexes guide_tags(:name_nl), :as => 'tag_names_nl', :separator => ' '
indexes guide_tags(:name_fr), :as => 'tag_names_fr', :separator => ' '
indexes guide_tags(:name_pt), :as => 'tag_names_pt', :separator => ' '
indexes places(:city_id), :as => 'indexed_city_id', :separator => ' '

has places(:city_id), :as => :city_ids
has :created_at
has :guide_places_count
has :likings_count
has :comments_count
```

  end

After indexing, I ran like ModelName.search its showing error like:
ThinkingSphinx::SphinxError: no enabled local indexes to search

**Comment by MaicolBen** [comment]
I have the same problem, what was it finally?

**Comment by pat** [comment]
Hi Maicol, feel free to open a new issue and we can discuss the specifics of your situation there.

**Comment by JochenFromm** [comment]
I had the same problem and the same error "no enabled local indexes to search thinking sphinx", which happened because I had two applications which share a common database and the same Sphinx server but have slightly different ThinkingSphinx settings in the Index classes. For me a `rake ts:rebuild` solved it, a `rake ts:regenerate` alone did not help.
