### ISSUE TITLE
ActiveRecord default_scope ignored

### ISSUE THREAD

**Issue by pioz** [pat/thinking-sphinx#740]
I've a Request class:

```
class Request < ActiveRecord::Base
    default_scope -> { where('user_id IS NOT NULL') }
    ...
end
```

When I search with Thinking Sphinx 3.1.0 `Request.search` I get all requests, ignoring the default scope.

Is there a way to consider the default scope?

**Comment by hafsabatool7** [comment]
I tried to use default_scope this way but it does not work. 
`@results = ThinkingSphinx.search(
      params[:search],
      classes: [SaleOrder, PurchaseOrder, Medicine,
                Doctor, Staff, Patient, Department]
    )`

I tried called search like this. However, even when I have default scope specified in each of these models/classes, it won't work. PLEASE HELP!

**Comment by pat** [comment]
Hi @hafsabatool7 - as noted in [an early comment in this thread](https://github.com/pat/thinking-sphinx/issues/740#issuecomment-35885196) default ActiveRecord scopes aren't used in search calls because searches aren't SQL calls to your database - they're instead SphinxQL calls to Sphinx.

There _is_ the option of [having Sphinx scopes](https://freelancing-gods.com/thinking-sphinx/v4/scopes.html) - however, these apply only on single-model searches. Your example is searching across many models, and thus there's no central source for scopes - a search on many models is a single query to Sphinx, not separate queries per model, so combining the scopes from different models into the single query is not possible.

**Comment by hafsabatool7** [comment]
@pat Thank you for your response.
