### ISSUE TITLE
Show warning when guard file exists

### ISSUE THREAD

**Issue by JHeidinga** [pat/thinking-sphinx#784]
Pat, 

Thanks a lot for your effortless coding and helping of others. I have had the pleasure of using your well written gem (an example of how it should be done) and reading through a lot of thinking-sphinx issues in which you helped out every time. Respect!

Not as much of an issue, but more an idea...
I've spend quite a few hours figuring out why one specific model was not delta indexing on our production environment, but was on our development environment. As it turns out, a simple guard file was set for this model in db/sphinx/production. Because of this file, the model is thrown out of the index at the very last moment indexing occurs in:

thinking-sphinx/lib/thinking_sphinx/controller.rb:6
    indices = indices.reject { |index| File.exists? guard_file(index) }

Would it be an idea to log a warning when this happens?

**Comment by mjsommer** [comment]
Pat, I am using TS w/ Sidekig via your ts-sidekiq-delta gem, creating multiple rows in one db transaction, and seeing your "Sphinx Guard file for index (file.name) exists, not indexing: ..." message multiple times in the log.

Two things, 

1) I looked at your referenced 524d019 code, and see that you have this as a "warn". 

2) The newly added data "is" indexed, so the process appears to work.

If I am adding 500(+) rows in one transaction, a) are these "warnings" perhaps due to racing conditions between saves and indexing, b) can I ignore them, and/or c) is there something I should do, to prevent this behavior?

Fyi, I plan to save up to 10,000 rows per transaction.

Thanks again,
Martin

**Comment by pat** [comment]
The warnings are very likely caused by race conditions. I'd recommend suspending deltas while inserting/updating these rows.

```ruby
ThinkingSphinx::Deltas.suspend :forum_post do
  # all the inserts
end
# a single delta index call is invoked afterwards.
```

If you're updating records, not just inserting, and you want the old record data to be ignored in the core index, use `suspend_and_update` instead of just `suspend`, and that'll mark all delta records as deleted in the core index as well as processing the delta index just once.

**Comment by mjsommer** [comment]
Thanks Pat, I also see your post:

    ThinkingSphinx::Deltas::IndexJob.new(‘forum_post_delta').perform

So, in addition to this, I am I am integrating the new Postgres 9.5 "upsert" (ON CONFLICT DO UPDATE). I initially used ActiveRecord create statements, but may need to revert to raw SQL, to get the upsert integarted.

Any thougths on Postgres' new "upsert", and how that may play with your TS Delta Indexing?

Thanks again!
Martin

**Comment by pat** [comment]
Given updates may happen, you'll want to make sure your upsert call is setting delta to true in both insert and update cases, and use `suspend_and_update` as noted before - this will ensure that records are marked appropriately, and the core index will be up-to-date as much as possible alongside the delta update.

Just to be clear: both the `suspend` and `suspend_and_update` calls will automatically do the delta indexing for you. You won't need to make a call via `ThinkingSphinx::Deltas::IndexJob` manually.

**Comment by mjsommer** [comment]
Genus Patrick, genius!!

Fyi, the suspend wraps the transaction, vs vice versa:

    ThinkingSphinx::Deltas.suspend_and_update :product do
      begin
        AffiliateCjProduct.transaction do

Thanks again!
Martin
