### ISSUE TITLE
MySQL sort_buffer_size problem

### ISSUE THREAD

**Issue by bistline** [pat/thinking-sphinx#819]
I'm having an issue with large indices and sort_buffer_size.  I work in a controlled distributed environment where I don't have the option of setting this configuration parameter for MySQL on a shared server, and I'm unable to index my database because it keeps running out of memory.  Is there a way to pass this as a parameter when trying to run rake ts:index in a production environment?  I tried setting the mem_limit option in thinking_sphinx.yml and it had no effect.  I got around the issue in development because I can up the limit on my machine, but the production MySQL server is shared amongst multiple groups and the DBAs refused to up the limit for performance reasons.

I'm using MySQL 5.6 and InnoDB.

**Comment by pat** [comment]
@madhuri033 are you using MySQL or PostgreSQL as your database? If you're using MySQL, it's worth noting that the `sort_buffer_size` setting may need to be increased at the database configuration level itself (e.g. the `my.cnf` file) to ensure the available upper limit is high enough (I'm guessing connection-level settings can only obtain whatever the server maximum is).

However, getting too carried away with modifying `sort_buffer_size` is not recommended:
https://www.xaprb.com/blog/2010/05/09/how-to-tune-mysqls-sort_buffer_size/

I would recommend instead removing the `sortable: true` flag from fields that do not need it - and in particular, I'm guessing the `post_description` field perhaps doesn't need to be sorted in Sphinx queries? If it's a text column (rather than varchar/length-limited string), then sorting certainly doesn't feel appropriate.
