### ISSUE TITLE
Error classes encapsulation 

### ISSUE THREAD

**Issue by tubaxenor** [pat/thinking-sphinx#903]
From: https://github.com/pat/thinking-sphinx/blob/v3.1.3/lib/thinking_sphinx/connection.rb#L89-L93

It seems like now errors are all gathered under `ThinkingSphinx::SphinxError`, may I ask the reason of  this change? Saw it began from https://github.com/pat/thinking-sphinx/commit/25d9bb16151943c0256e3856ba2b098ee0e9ec38

The reason why I am asking is because this hides some riddle errors like `Riddle::OutOfBoundsError` which can now be catch/rescue by parsing the error message instead of class matching.

**Comment by pat** [comment]
Firstly, sorry for not responding sooner. Life's been a little hectic lately.

Riddle's OutOfBoundsError no longer is in play, because Thinking Sphinx v3 does not use Sphinx's binary protocol (which is the protocol Riddle uses to communicate with Sphinx). Instead, it uses the SphinxQL protocol, which operates like a MySQL server (hence using the `mysql2` gem).

So, that generic `rescue` line is capturing errors from communicating with Sphinx via `mysql2`, and the reason I'm wrapping those in SphinxError is to distinguish between MySQL databases (people were finding the MySQL reference in exceptions confusing when they came from Sphinx instead).

Of course, the end result is that yes, you'll currently need to parse the error message yourself to know if it's related to out-of-bounds issues. I'd be open to a patch for `ThinkingSphinx::SphinxError.new_from_mysql` which did that message parsing and returned a `ThinkingSphinx::OutOfBoundsError` instead, if you want to investigate that?
