### ISSUE TITLE
Accessing distance attribute when returning json.

### ISSUE THREAD

**Issue by mikemerritt** [pat/thinking-sphinx#908]
When using ``to_json`` to output search results as json I am unable to include the distance attribute when using geodist search. Using ``methods: [:distance]`` with ``to_json`` does not work. Is there a built in way for passing the distance attribute when converting sphinx results into json? If not, it would be nice to have a way to easily include it in the rendered json data as distance is a pretty critical piece of data when doing geodist searches.

**Comment by pat** [comment]
Hi Mike

Thinking Sphinx does not insert the `distance` method into the appropriate model instances (because that's a little too invasive/presumptive for my liking), but instead wraps each model instance inside a new object which also has a distance method. Anything not handled by that wrapper is passed through to the model instance, hence `to_json` will end up calling the model, without the context of the distance from Sphinx.

This may be a way around it:

```ruby
class JsonPane
  def initialize(context, object, raw)
    @context, @object, @raw = context, object, raw
  end

  def as_json_with_distance(options = nil)
    @object.as_json(options).merge('distance' => @raw['geodist'].to_f)
  end
end

search = Model.search 'foo', :geo => [lat, lng]
# Must call the next line before looking at values. If you're running this in a Rails console, put `; ''` at the end of the previous line to avoid `search` having `inspect` called on it.
search.context[:panes] << JsonPane
search.collect(&:as_json_with_distance).to_json
```

It's worth noting that panes are not allowed to override methods that already exist on the model instance (the `object` argument), hence the pane does not define `as_json` or `to_json`.

**Comment by mikemerritt** [comment]
Thanks, very helpful. It would be nice if this were somehow integrated directly into TS with maybe some sort of ``results_to_json`` method.

**Comment by pat** [comment]
I'll certainly consider it - but this is the first time this issue's been raised, so right now, I'd say such integration is unlikely - especially given the plethora of JSON-generating approaches.
