### ISSUE TITLE
Add support for delta merging into main index

### ISSUE THREAD

**Issue by jogaco** [pat/thinking-sphinx#919]
This would be particularly useful for large indexes.
I could perhaps implement this. What do you think?

**Comment by pat** [comment]
Firstly, an apology: I aim to reply to every issue or PR promptly! To have no reply at all (even though I added a label) is terribly rude, and not only because you offered to help with implementation! Sorry! :(

You're not the first to request merging support. I did run some tests against Sphinx many years ago for merging, and found it wasn't reliable. I've finally revisited this, and it seems to be stable now, which is good news.

The even better news: I spent some time over the last few days implementing merging support, first in Riddle (which is part of the v2.3.0 release), and then building on top of that in Thinking Sphinx. The results are currently in [a feature branch](https://github.com/pat/thinking-sphinx/compare/feature/merging), but the acceptance tests are passing, so I'm pretty happy for this feature to be considered done, at least as a simple level. `rake ts:merge` does what's needed for every delta index that's present.

I want to add some unit specs in - and possibly the ability merge a single model's delta - before merging the branch into develop. From there, it will be part of the next gem release (I'm as yet undecided whether it'll be 3.5.0 or 4.0.0).

I'll close this issue once the changes are in the `develop` branch. Testing is certainly welcome in the meantime, if it turns out this is still a feature you're interested in two and a half years later!

**Comment by jogaco** [comment]
Amazing!
The project I intended to use this for is now phased down, but I might use this for another one.
I'll let you know if I can contribute with some tests.

**Comment by pat** [comment]
Just merged this into the `develop` branch - there are unit specs, and the `INDEX_FILTER` environment variable can be used to specify specific indices to merge (use the index name minus the `_core`/`_delta` suffix).

I'm now thinking the upcoming release will be 4.0.0 - there are a few things to clean up, plus it'd be nice if Rails 5.2.0 got released soon so I can know it supports it well. Hopefully it'll all come together in the next few weeks!

And yes, if you do find another project where TS fits what you need, I'll be keen to hear how you go with using this feature :)
