### ISSUE TITLE
Don't know how to build task 'thinking_sphinx:index'

### ISSUE THREAD

**Issue by dborovsky** [pat/thinking-sphinx#927]
Hi

I use:
gem 'mysql2',          '~> 0.3.18', :platform => :ruby
gem 'thinking-sphinx', '~> 3.1.4'

ruby 2.0.0p247
Rails 3.2.18

I downloaded project from github and want to run.

I calling command rake db:migrate, error - Don't know how to build task 'thinking_sphinx:index'. What am i doing wrong and how solve this problem?

**Comment by pat** [comment]
The task `thinking_sphinx:index` does not exist with v3 - it's just `ts:index` now. If you're not calling that manually, something in your code is… does `rake --trace db:migrate` provide any clues to where that outdated code might be?

**Comment by dborovsky** [comment]
![screenshot from 2015-07-08 14 54 43](https://cloud.githubusercontent.com/assets/3728303/8569543/655a4c7a-2581-11e5-9401-9cd859e28bed.png)

Its  trace. Can you help? What to look for?

**Comment by pat** [comment]
The error is coming from the ts-resque-delta gem - you should upgrade that to v2.0.0.

**Comment by dborovsky** [comment]
1. i upgrated ts-resque-delta gem to 2.0.0.
2. removed all versions gem thinking-sphinks
3. install again gem 'thinking-sphinx', '~> 2.0.14'

Now i have next versions:
Sphinx 2.0.4-id64-release (r3135)
thinking-sphinx (2.0.14)
mysql2 (0.3.18)

when rake db;migrate , display error:  Resque::Helpers will be gone with no replacement in Resque 2.0.0.
Resque::Helpers will be gone with no replacement in Resque 2.0.0.
rake aborted!
NoMethodError: undefined method `before_index_hooks' for ThinkingSphinx:Module

**Comment by pat** [comment]
Why did you drop thinking-sphinx back to 2.0.14 when you were using 3.1.4 previously?

**Comment by dborovsky** [comment]
becose team developers in project using 2.0.14 v. I want also run project with current version.

**Comment by pat** [comment]
Okay, well you have three options:

* Use Thinking Sphinx v2.0.14 and ts-resque-delta 1.2.4
* Use Thinking Sphinx v2.1.0 and ts-resque-delta 2.0.0
* Use Thinking Sphinx v.3.1.4 and ts-resque-delta 2.0.0

The last is the best option, because while you'll have some pain upgrading Thinking Sphinx now, then it's out of the way and further upgrades will be easier. Upgrading is covered here:
https://github.com/pat/thinking-sphinx#upgrading

If you want to use the latest ts-resque-delta, then TS v2.1.0 should have all the changes required to work.

**Comment by dborovsky** [comment]
Thank you, Pat!
