### ISSUE TITLE
Some improvement possibilities

### ISSUE THREAD

**Issue by dreyks** [pat/thinking-sphinx#932]
Hi there.

I've been fiddling with TS for a couple of days and came up with some needed (by me) monkeypatches which may possibly be interesting for you to include into gem.

These are some quick-n-dirty fixes but if you like the idea I will gladly turn each of them into a proper pull-request with tests, code-style etc.

https://gist.github.com/dreyks/13182f572c7ed38b7d4e

What do you think?

Oh and starting from sphinx 2.2.1 (i think) there's a new nice keyword `FACET` which makes facet search much easier. Are you planning to use it?

**Comment by pat** [comment]
Hi Roman

Thanks for all these suggestions, and your patience given it's taken me a little while to respond. Some thoughts going through each patch:

1. **Fixing incorrect quoting of full table names**: This one makes sense, and I know you've opened a standalone issue for it. A pull request would be great.
2. **Removing `:sql => {:order ... }` support**: Rather than removing the feature, I'd rather get to the bottom of what's causing the underlying bug instead.
3. **Storing STI class names**: I *think* I grok this - and if so, sounds like a good move (especially with an acceptance test or two in place to confirm the expected behaviour).
4. **Allowing searching on ActiveRecord scopes**: Not yet sold on this one - the mixing of Sphinx and SQL queries can potentially open up a whole basket of confusion. Technically, I get your solution, it's more thinking about the ongoing support of such a feature and the complications of handling support questions around it that makes me nervous.
5 **`:include` becomes `:includes`**: smart move, a pull request would be great.
6 **Facet filter fix**: Given it sounds like a bug, a fix would be great. The `const_get` call makes me pause, though… but that wouldn't be needed if implemented in TS proper, right?

**Comment by dreyks** [comment]
Hi there!
Totally understand the lack of time, we've all got something to do besides opensource =)

So. I hope I'll have some time this weekend and I'll start killing this off one by one starting from the easiest.

The hardest one is the `:sql => {:order ... }` cause I'm not really sure of your intentions there. But that will have to wait till it's time comes.

yeah `const_get` is a consequence of monkey-patching, it'll be gone when it comes to the core

**Comment by dreyks** [comment]
one down, proceeding =)

**Comment by pat** [comment]
As part of some tidying up of my open source repos, I'm going to close this issue. Clearly they've not been a priority for either of us (which is completely fine!) - and I'm still happy to consider such changes, so if you find you do want to have another go at any of these, that'd be great. Given it's been a few years though, I'm not expecting anything :)
