### ISSUE TITLE
ThinkingSphinx::ConnectionError asynchronous connection

### ISSUE THREAD

**Issue by aibraimov** [pat/thinking-sphinx#934]
My rails project running on nginx + passenger, in future I am going to update it nginx + thin (3 processes). But I noticed that thinking sphinx  cannot respond to asynchronous connections. I run in two tabs on browser search query, and one of the responses returned this error:
<pre>Error connecting to Sphinx via the MySQL protocol. Error connecting to Sphinx via the MySQL protocol. Can't connect to MySQL server on '127.0.0.1' (111) ...</pre>

thinking_sphinx.yml:
<pre>
development:
  quiet_deltas: true
  mysql41: 9311
  bin_path: "/usr/bin"  
  searchd_binary_name: searchd
  indexer_binary_name: indexer
  min_infix_len: 3
  min_word_len: 2
  html_strip: 1
  index_exact_words: 1
  min_stemming_len: 4
  charset_type: "utf-8"
test:
  mysql41: 9311
production:
  mysql41: 9311
</pre>
No such problems on localhost, server on WebRick. What could I do, to avoid this. There is only one thinking-sphinx process. Maybe I can increase it's number. Thanks in advance!

<b>Update</b>

I rebuilt thinking sphinx, I haven't done it for long time, now it doesn't falling, maybe thing was in it. But I am still interested in how to run several ts processes, or it is unecessary.

**Comment by pat** [comment]
Sorry for not responding sooner - Sphinx should work fine with multiple connections on a single daemon, so you shouldn't need to change Thinking Sphinx's settings in any way to have this work. But perhaps you were using an old version of Sphinx or Thinking Sphinx where there were issues? It sounds like you've perhaps upgraded Sphinx (rather than Thinking Sphinx) which is what's resolved the issue.
