### ISSUE TITLE
FATAL: no indexes found in config file 'my_app_path/config/development.sphinx.conf'

### ISSUE THREAD

**Issue by RathanakSreang** [pat/thinking-sphinx#937]
Hi, I try to run

```sh
rake ts:index
```
it show 
using config file 'my_app_path/config/development.sphinx.conf'...
FATAL: no indexes found in config file 'my_app_path/config/development.sphinx.conf'
but it don't not generate the index for me, do you know why?

**Comment by pat** [comment]
Which versions of Rails and Thinking Sphinx are you using? And what is your index definition for the model looking like?

**Comment by RathanakSreang** [comment]
I use:
- rails 4
- thinking-sphinx v3.1.4
and in model I define like this:

```ruby
define_index do
  indexes content
  indexes :name, :sortable => true
  indexes comments.content, :as => :comment_content
  indexes [author.first_name, author.last_name], :as => :author_name
  
  has author_id, created_at
end
```

**Comment by pat** [comment]
Okay, since version 3, TS has a different approach to defining indices, as covered by the documentation: http://freelancing-gods.com/thinking-sphinx/indexing.html

You want to create a file in `app/indices` - if your model is named Article, then call it `article_index.rb`, and inside, you'd so the following (though you'll likely need to change the model name accordingly):

```ruby
ThinkingSphinx::Index.define :article, :with => :active_record do
  indexes content
  indexes name, :sortable => true
  indexes comments.content, :as => :comment_content
  indexes [author.first_name, author.last_name], :as => :author_name

  has author_id, created_at
end
```

Try making that change - and removing the `define_index` block from your model - and running `rake ts:rebuild`.

**Comment by RathanakSreang** [comment]
@pat 
Ok, let's me try.
