### ISSUE TITLE
FATAL: failed to lock Resource temporarily unavailable, will not index.

### ISSUE THREAD

**Issue by atomical** [pat/thinking-sphinx#948]
```
FATAL: failed to lock /var/..../mobile_user_delta.spl: Resource temporarily unavailable, will not index. Try --rotate option.
```
Is there a way I can prevent this from happening? I ran `rake ts:index` when I got this error. We're also using ts-sidekiq-delta. Could that cause a race condition?

**Comment by pat** [comment]
I've finally added something that will deal with this: d12e74130a131e9b8f2ac60a250182da5d13215e

The new one-at-a-time indexing strategy will mean that `ts:index` processes each index one-by-one, instead of all at once. This is a little slower, but it'll mean that any delta updates that run at the same time won't cause the full indexing procedure to die an untimely death.

You can configure it like so:

```ruby
ThinkingSphinx::Configuration.instance.indexing_strategy = ThinkingSphinx::IndexingStrategies::OneAtATime
```

This may become the default behaviour at some point in the future - I'm not yet sure.

**Comment by atomical** [comment]
Would this change effect the consistency of the index? Or merely prevent errors? The sidekiq job should retry.

**Comment by pat** [comment]
The only scenario I can think of where the data won't be entirely consistent:

* Sidekiq is running a delta index just as the rake task gets around to processing that same delta index.
* Sidekiq runs successfully.
* Rake task fails on that delta index, but continues with the rest.

At this point, that delta index may be missing records that were changed after the Sidekiq job started. Given how fast the Sidekiq job should be, and the fact that the core index will have just been processed as well, the odds of this happening are slim, and will only persist until that delta is next processed (so, if a particular model is being updated regularly, the data will be eventually consistent.

**Comment by atomical** [comment]
I'm getting the error:

NoMethodError: undefined method `indexing_strategy' for #<ThinkingSphinx::Configuration:0x007f9da977ee00>

when I try to set this in an initializer.

**Comment by pat** [comment]
You'll need to update to TS v3.2.0 (or use a git reference in your Gemfile) to have access to this feature.
