### ISSUE TITLE
sql_query_pre became sql_query_post_index after upgrading

### ISSUE THREAD

**Issue by pixways-abarbotte** [pat/thinking-sphinx#958]
Hi,

I expose our versions first 

We were like this in our previous application : 
-ruby 1.9.2p290 (2011-07-09 revision 32553) [x86_64-linux]
-rails (3.2.18)
-Sphinx 2.0.1-beta (r2792)
-thinking-sphinx (2.0.9)
-ts-delayed-delta (1.1.3)

Now we are here : 
-ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-linux]
-rails (4.2.1)
-Sphinx 2.2.6-id64-release (r4843)
-thinking-sphinx (3.1.3)
-ts-delayed-delta (2.0.2)

And we encounter a strange thing when we are generating our production.sphinx.conf file 
with rake ts:configure
It is about delta in index_core

In previous version, it was generating like this
sql_query_pre = UPDATE `images` SET `delta` = 0 WHERE `delta` = 1

But now, this query is generated like this
sql_query_post_index = UPDATE `images` SET `delta` = 0 WHERE `delta` = 1

Did someone can help me about this ?
I can provide more explanations/details if needed 

Thanks in advance

**Comment by pat** [comment]
This was changed at some point in TS v3. Here was the issue with the old approach:

* Have a lot of images, thus processing the core image index is slow.
* Have a bunch of delta changes covered by the delta index (let's call these DELTA A).
* Begin processing of core image index: all delta records _immediately_ have their delta flag set to false.
* While core index is being processed, a delta processing request comes through: a single record has their delta flag set to true, and the delta index is updated with _only_ that record (let's call this DELTA B).
* Until the core index finishes updating, the daemon will no longer have access to the DELTA A changes - they're not in the old core index, nor the new delta index.

Now, the behaviour is as follows:

* Have a lot of images, thus processing the core image index is slow.
* Have a bunch of delta changes covered by the delta index (DELTA A).
* Begin processing of core image index: the core index includes all records, no matter what the delta flag is set to.
* While core index is being processed, a delta processing request comes through: a single record has their delta flag set to true, and the delta index includes that record (DELTA B) and everything else with delta set to true (DELTA A).
* While the core index finishes updating, the daemon has access to both DELTA A and DELTA B.

… although, now that I think about it, this approach means that when the core index has finished processing, DELTA B won't be available, because the delta index will update after the core index, but all delta flags will be false. The core index will include DELTA A, but DELTA B will be forgotten. I'll think about how we can get around this…

**Comment by pixways-abarbotte** [comment]
ok, thanks for the explanation.
For our use of it, the old approach was good (better) because time indexing is very short (approx 20min) with this version instead of old version (approx 8hours) 
So the time that delta A is unavailable for a little moment.

Now, the problem is new pictures arriving during the rebuild are new and marked as delta=0
So available only at next rebuild (+1day)

**Comment by pat** [comment]
Okay, I've reverted this behaviour in the develop branch (see ac1529a9ad99bd39a9d3b279b96e497d589d70f8), so sql_query_pre is used again for resetting the delta flags. It's still not ideal, but I think it's better to have the data be consistent by the time a full index finishes, rather than waiting until the next time the task is called (which in your case could be a full day).

**Comment by pixways-abarbotte** [comment]
Okay, great, thanks a lot !

I'm not a developper but perhaps it is possible to add a parameter into thinking_sphinx.yml , like delta_sql_query = [pre] / [post] 
just to allow anybody to choose what is better for its use...
