### ISSUE TITLE
Distributed / Sharded Index

### ISSUE THREAD

**Issue by nartz** [pat/thinking-sphinx#963]
Does TS Support creating a distributed / sharded index somehow? I seem to have too many rows at this point and need to speed up searching. Or would i just have to manually configure the sphinx.conf?

**Comment by pat** [comment]
What you can do is define multiple indices with specific ranges of ids (or some other column, if that's preferred), and because they'll all be for the same model, all results will be returned when searching for that model (and there will be a distributed index created as well).

Here's a basic example:

```ruby
offset  = 0
window  = 10_000
maximum = Article.maximum(:id)

while offset < maximum do
  ThinkingSphinx::Index.define(
    :article, :name => "article_#{offset}", :with => :active_record
  ) do
    # fields
    # attributes
    
    where "articles.id > #{offset} AND articles.id <= #{offset + window}"
  end
  
  offset += window
end
```

**Comment by nartz** [comment]
ok awesome!
