### ISSUE TITLE
sentence as search query doesn't match indexed words

### ISSUE THREAD

**Issue by agenteo** [pat/thinking-sphinx#966]
I would like `ThinkingSphinx.search("how to ski in the mountains")` to match records that have `ski` in their title but I haven't found the way yet.

When I search for "ski" it does find the record confirming the index has that information.

I've done a bit of search online and found "mode:any" as the claimed solution from people trying to solve this with sphinx. I added that to the search string `ThinkingSphinx.search("how to ski in the mountains;mode:any"') in thinking sphinx but no luck.

Is this a missing feature from TS or did is it just not possible in sphinx? Thanks

**Comment by pat** [comment]
Hi Enrico!

If you're using TS v3, then it's worth noting that _all_ queries use the extended match mode, as it's done via the SphinxQL protocol, which has no concept of other (older) - match modes. To get 'any' behaviour in TS v3 queries, you need to separate each word with single pipes as an OR operator: `"how | to | ski | in | the | mountains"`.

If you're using TS v2 - which still uses the old binary protocol - then you can add a `:match_mode => :any` option to your search call.

However, it sounds like the issue is actually that Sphinx is not returning results which have all the words "how to ski in the mountains", which certainly sounds like a bug in Sphinx itself. Which version are you using?

**Comment by agenteo** [comment]
Sphinx 2.2.10 on the latest TS.

Using pipes as separator of the search query words worked.

Thanks Pat!
