### ISSUE TITLE
Application with sphinx but connected to searchd on different machine (VPS, not on Flying Sphinx)

### ISSUE THREAD

**Issue by agungyuliaji** [pat/thinking-sphinx#991]
```ruby
rake aborted!
Configuration file '/app/config/staging.sphinx.conf' does not exist
/app/vendor/bundle/ruby/2.3.0/gems/riddle-1.5.12/lib/riddle/controller.rb:100:in `check_for_configuration_file'
/app/vendor/bundle/ruby/2.3.0/gems/riddle-1.5.12/lib/riddle/controller.rb:31:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/thinking-sphinx-3.2.0/lib/thinking_sphinx/rake_interface.rb:61:in `start'
/app/vendor/bundle/ruby/2.3.0/gems/thinking-sphinx-3.2.0/lib/thinking_sphinx/tasks.rb:44:in `block (2 levels) in <top (required)>'
```
seems still leads to Heroku filesystem

**edited**
here the configuration file
```yaml
staging:
  address: <ip sphinx installed>
  mysql41: 3200
```

**Comment by pat** [comment]
Are those the only settings you have? I'd recommend setting up some fixed paths (especially if you're using Capistrano or another tool that has per-release directories): http://freelancing-gods.com/thinking-sphinx/deployment.html

Also: Flying Sphinx modifies the configuration file only within its own context - it doesn't send the file back to your app - so the paths shouldn't be from there, even if you were using FS previously.

**Comment by agungyuliaji** [comment]
Ah!! thanks for the link :) i missed that.
It is possible or any way Rails 4 on Heroku use Sphinxsearch without Flying Sphinx Addons? 

> http://freelancing-gods.com/thinking-sphinx/deployment.html
Please make sure all of the above files (configuration file, pid file, index files, binlog path) are located in a shared directory (instead of a directory tied to a specific deployed release). Otherwise, running rake tasks will become difficult and unreliable.

**Comment by pat** [comment]
You can't run Sphinx directly on Heroku dynos - it just doesn't fit their 12-factor approach. You could run a separate server somewhere (on AWS is probably wise, to minimise latency) with a copy of your Rails app and run all the TS tasks on that instance, with your Heroku app using the appropriate IP and port.

Of course, that could be expensive and adds a lot of hassle, which is precisely why I built Flying Sphinx (because I had my own Heroku apps that I wanted to use Sphinx with). Is there a reason why Flying Sphinx doesn't suit your needs?

**Comment by agungyuliaji** [comment]
No problem with Flying Sphinx. actually very helpful 👍 
The reason is just something internal. Thanks 😄
