### ISSUE TITLE
Recreating an index on a migration table

### ISSUE THREAD

**Issue by infiton** [pat/thinking-sphinx#993]
We have an active record table that is indexed using thinking-sphinx that has ~50 million rows. Every so often we need to to ETL a migration table of the same size. To do this quickly we upload the table as `table_<uuid>` and then do a table rename `table -> table_migrated_<uuid>` and `table_<uuid> -> table`

This works great, however once we do this we need to fully rebuild the sphinx index for this table which can take ~2 hours. 

What I would like to do is prebuild the sphinx index on the migration table before the rename and then `stop searchd -> swap out index files -> start searchd`. Is there a way I can use the thinking sphinx configuration and just point the sphinx index for this table at the migration table `table_<uuid>`?

**Comment by pat** [comment]
Hi Kyle

This is certainly not an easy thing to work through… but, TS uses the model's table name, so in theory you could have something like the following in your model:

```ruby
class Foo < ActiveRecord::Base
  self.table_name = ENV['FOO_TABLE_NAME'] if ENV['FOO_TABLE_NAME'].present?
  # ...
```

And then use the appropriate environment variable to run `rake ts:configure`. Then it might be best to process just the specific Sphinx index:

```
indexer --config config/production.sphinx.conf --rotate foo_core
```

Then, once you're ready, run ts:configure again without the environment variable to ensure the generated configuration file is using the original table name.

If you've got delta indexing in play, though, that could complicate things, because it'll be referring to the latest Sphinx configuration file each time a change is processed. Maybe that's okay? Depends on the behaviour you're after, I guess. And of course, everything I've just suggested is just an idea, I've not delved into trying it out myself.

Although, I'm curious: why is a rebuild necessary? Are you changing your Sphinx index structure as well as your database structure? If not, you could just use `rake ts:index` instead and avoid the need to take Sphinx down for a couple of hours.

**Comment by infiton** [comment]
Hi Pat,

Thanks for the response, I'll see if I can get this direction to work.

The reason the rebuild is necessary is because the primary key structure of the new table will be different from the old table. I.e. in the old table there could be a row `id: 1, first_name: "Foo", last_name: "Bar"` but in the migrated table the row could be `id: 13, first_name: "Foo", last_name: "Bar"` (the reason has to do with an external id that is actually a more important index so the table is built ordered on this id so that the mysql index is as efficient as possible). I believe that for this reason the entire sphinx index needs to be rebuilt or using the old index `search: "Foo Bar"` would point to `1` which is no longer the case.

**Comment by pat** [comment]
A full processing of the index (as covered by the `rake ts:index` task) is certainly needed in this case, but a rebuild (`rake ts:rebuild`) is unnecessary - you only need to have Sphinx stopped/started if the _structure_ of any index changes (new/altered fields or attributes), or if you're adding/removing indices.

Processing the indices will ensure the data is updated accordingly.

However, given the primary keys would be changing… in the previous suggestion, as soon as the Sphinx indexer command finishes, Sphinx would have the new data, so from that point in time until your app is using the new version of the table, Sphinx and your Rails app/db won't be in sync. Still, that window of time should be much smaller than waiting for a full index, let alone a rebuild.

**Comment by infiton** [comment]
Thanks for the help! This strategy worked.

The migration happens inside an object (with a uuid `slug` and a `tmp_dir` for work) that orchestrates it so I added two methods:

```ruby
def generate_sphinx_indices
  ts_config = ThinkingSphinx::Configuration.instance

  begin
    FooModel.table_name = migration_table.name

    ts_config.configuration_file = tmp_config_path
    ts_config.indices_location = tmp_indices_location
    ts_config.searchd.binlog_path = "#{tmp_dir}/binlog/#{slug}"
    ts_config.searchd.log = "#{tmp_dir}/#{slug}.searchd.log"
    ts_config.searchd.pid_file = "#{tmp_dir}/#{slug}.sphinx.pid"
    ts_config.searchd.query_log = "#{tmp_dir}/#{slug}.searchd.query.log"

    ts_config.render_to_file

    FileUtils.mkdir_p ts_config.indices_location
    ts_config.controller.index(verbose: true)
  ensure
    FooModel.table_name = "foo_models"
    ThinkingSphinx::Configuration.reset
  end
end

def swap_sphinx_indices
  ts_interface = ThinkingSphinx::RakeInterface.new
  ts_config = ThinkingSphinx::Configuration.instance

  ts_interface.stop
  current_sphinx_indices_location = ts_config.indices_location
  migrated_sphinx_indices_location = "#{tmp_dir}/migrated/sphinx"

  FileUtils.mkdir_p migrated_sphinx_indices_location
  FileUtils.mv(current_sphinx_indices_location, migrated_sphinx_indices_location)
  FileUtils.mv(sphinx_indices_location, current_sphinx_indices_location)

  ts_interface.start
end
```

**Comment by pat** [comment]
Great to know you've got it working - and thanks for sharing the solution! :)
